language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: true
      dist: trusty
      env: TARGET_DIST=trusty
    - os: linux
      compiler: gcc
      sudo: true
      dist: precise
      env: TARGET_DIST=precise

addons:
  apt:
    sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main'
          key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
        - sourceline: 'deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main'
          key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
    packages:
    - gcc-4.8
    - g++-4.8
    - build-essential
    - libcap-dev
    - flex
    - bison
    - libelf-dev
    - git
    - libtool
    - libpixman-1-dev
    - minisat
    - zlib1g-dev
    - libglib2.0-dev
    - clang-3.4
    - llvm-3.4
    - llvm-3.4-dev
    - llvm-3.4-tools

before_install:
    - export CRETE_SRC=`pwd`
    - cd ../
    - mkdir build
    - cd build/
    - export BUILD_DIR=`pwd`

    - if [[ "$TARGET_DIST" == "precise" ]]; then
         wget https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz;
         tar xf cmake-3.9.1.tar.gz; cd cmake-3.9.1;
         ./bootstrap; make -j; sudo make install; cmake --version;
      fi

    - cd $BUILD_DIR
    - CXX=`which clang-3.4` cmake $CRETE_SRC;

script:
    # Build CRETE
    - make -j6
